export type SkeletonThemeVars = {
  skeletonParagraphHeight?: string;
  skeletonParagraphBackground?: string;
  skeletonParagraphMarginTop?: string;
  skeletonTitleWidth?: string;
  skeletonAvatarSize?: string;
  skeletonAvatarBackground?: string;
  SkeletonImageSize?: string;
  SkeletonImageRadius?: string;
  skeletonDuration?: string;
  skeletonBackgroundFrom?: string;
  skeletonBackgroundTo?: string;
  skeletonPaddingHorizontal?: string;
  skeletonGridAvatarSize?: string;
  skeletonGridTextWidth?: string;
  skeletonGridGap?: string;
  skeletonCellAvatarSize?: string;
  skeletonMediaGap?: string;
  skeletonMediaAspectRatio?: string;
  skeletonMediaRowLeftWidth?: string;
  skeletonMediaRowRightWidth?: string;
};
