export type SliderType = 'single' | 'range' | 'node-range';

export type SliderThemeVars = {
  sliderActiveBackground?: string;
  sliderInactiveBackground?: string;
  sliderDisabledOpacity?: number | string;
  sliderBarHeight?: string;
  sliderActiveBarHeight?: string;
  sliderButtonWidth?: string;
  sliderButtonHeight?: string;
  sliderButtonRadius?: string;
  sliderButtonBackground?: string;
  sliderButtonBorderColor?: string;
  sliderButtonGripColor?: string;
  sliderButtonGripGap?: string;
  sliderMarkLabelColor?: string;
  sliderMarkLabelActiveColor?: string;
  sliderMarkDotColor?: string;
  sliderMarkDotActiveColor?: string;
  sliderMarkDotActiveBorderColor?: string;
  sliderValueMarginTop?: string;
  sliderValueColor?: string;
  sliderValueFontSize?: string;
  sliderValueLineHeight?: string;
  sliderValueActiveColor?: string;
  sliderInputsMarginTop?: string;
  sliderInputHeight?: string;
  sliderInputPaddingHorizontal?: string;
  sliderInputFontSize?: string;
  sliderInputColor?: string;
  sliderInputBackground?: string;
  sliderInputBorderColor?: string;
  sliderInputFocusBorderColor?: string;
  sliderInputPlaceholderColor?: string;
  sliderInputDividerWidth?: string;
  sliderInputDividerHeight?: string;
  sliderInputDividerGap?: string;
  sliderInputDividerColor?: string;
  sliderInputRadius?: string;
};
